!      Writes OFF and ASCII PLY files with color overlay

       subroutine WriteGeom(b,powmin,powmax,OFFNAME,PLYNAME)
       use io_functions, only : get_new_fileunit
       use cornea_arrays
       use set_precision, ONLY : wp
       use special_fct, only : rgb2, rgb5
       use ISO_FORTRAN_ENV, only: INT8,INT16,INT32,REAL32
       TYPE(wpRadSlopeMatrix),INTENT(IN) :: b
       character(len=*), intent(in) :: OFFNAME,PLYNAME
       real(wp), intent(IN) :: powmin,powmax 
       real(wp) :: X1,X2,X3
       real(REAL32) :: vert1,vert2,vert3,vert4
       real(wp) :: pow_vert1,pow_vert2,pow_vert3,pow_vert4,pow_face4,pow_face3_1,pow_face3_2
       integer :: i,j,M1,N1,vertices,faces,edges,unitno1,unitno3
       integer(INT32) :: ivert1,ivert2,ivert3,ivert4,vertnum
       logical :: donut,quad
       integer(int16) :: rgbv(3)  

!       RGB colors can follow after list of faces       
!       255 0 0 #red
!       0 255 0 #green
!       0 0 255 #blue
       
       N1=size(b%r,2)
       M1=size(b%r,1)

       unitno1 = get_new_fileunit()
       open(unitno1, file=trim(PLYNAME), action="write", iostat=ierr)
       unitno3 = get_new_fileunit()
       open(unitno3, file=trim(OFFNAME), action="write", iostat=ierr)
       
      donut = .TRUE.
      quad = .FALSE.
!     if no missing faces
      if (donut) then
       vertices=M1*N1
       if (quad) then
        faces=(N1-1)*M1    !quadrilaterals
        edges=(2*N1-1)*(M1-1)  ! don't do the last set of edges
       else
        faces=2*(N1-1)*M1  !triangles
        edges=(3*N1-2)*(M1-1)  
       endif
      else 
!      closed 
       vertices=M1*N1+1
       faces=(2*N1-1)*M1  !triangles
       edges=(3*N1-1)*(M1-1)  
      endif
!     write(12,*) vertices,faces,edges 
  
!      count the faces & edges, don't change the vertices or their numbering
       faces=0
       edges=0
       do i=1,M1-1
        do j=1,N1-1
        if  ( (j < b%MV(i)) .AND. (j < b%MV(i+1)) ) then           
         if (donut) then
          if (quad) then
           faces=faces+1
           edges=edges+2
          else
           faces=faces+2
           edges=edges+3
          endif
         else
!        nothing here yet for .donut. .EQ. FALSE
                 
         endif
         endif
        end do
       end do  
       
!       Last one is different
!       for i=M1
        do j=1,N1-1
        if  ( (j < b%MV(M1)) .AND. (j < b%MV(1)) ) then                     
         if (donut) then
          if (quad) then
           faces=faces+1
           edges=edges+2
          else
           faces=faces+2
           edges=edges+3
          endif
         else
!        nothing here yet for .donut. .EQ. FALSE

         endif
         endif
        end do 

!       HEADER for ASCII PLY
        write(unitno1,'(g0)') 'ply' 
        write(unitno1,'(g0)') 'format ascii 1.0'
        write(unitno1,'(g0)') 'comment Generated by Janus'
        write(unitno1,*) 'element vertex ',vertices         
        write(unitno1,'(g0)') 'property float32 x'        
        write(unitno1,'(g0)') 'property float32 y'       
        write(unitno1,'(g0)') 'property float32 z'      
        write(unitno1,*) 'element face ',faces     
        write(unitno1,'(g0)') 'property list uint8 int32 vertex_index' 
        write(unitno1,'(g0)') 'property uint8 red'
        write(unitno1,'(g0)') 'property uint8 green'
        write(unitno1,'(g0)') 'property uint8 blue'
        write(unitno1,'(g0)') 'end_header' 

!      HEADER for OFF 
       write(unitno3,'(g0)') 'OFF'
       write(unitno3,*) vertices,faces,edges

!      Write vertices as REAL32
!      There are "unreferenced vertices" this way, but it is much easier with vertex numbering                                                                   
       do i=1,M1
        do j=1,N1 
         X1=b%thta(i)
         X2=b%r(i,j)
         X3=b%Zp(i,j)   
         vert1 = ABS(X2)*COS(X1) 
         vert2 = ABS(X2)*SIN(X1) 
         vert3 = X3            
         write(unitno1,*) vert1,vert2,vert3
         write(unitno3,*) vert1,vert2,vert3 
        end do
       end do

!      these HAVE to be written/formatted as integers(INT32)
        
       do i=1,M1-1
        do j=1,N1-1
         ivert1=(i-1)*N1+j-1
         ivert2=(i-1)*N1+j
         ivert3=i*N1+j
         ivert4=i*N1+j-1

         if  ( (j < b%MV(i)) .AND. (j < b%MV(i+1)) ) then   

!        powers go by vertices, but colors need by face
!        pow=b%Zp(I,J) as of now, this is actually elevation
!        rgbv=rgb5(pow,powmin,powmax)
         pow_vert1=b%Zp(I,J+1)
         pow_vert2=b%Zp(I+1,J+1)
         pow_vert3=b%Zp(I,J) 
         pow_vert4=b%Zp(I+1,J)
         pow_face4=(pow_vert1+pow_vert2+pow_vert3+pow_vert4)/4
         pow_face3_1=(pow_vert1+pow_vert2+pow_vert3)/3
         pow_face3_2=(pow_vert1+pow_vert3+pow_vert4)/3
                   
          if (donut) then
           if (quad) then
            vertnum=4
            rgbv=rgb5(pow_face4,powmin,powmax)
            write(unitno1,*) vertnum,ivert1,ivert2,ivert3,ivert4,rgbv
            write(unitno3,*) vertnum,ivert1,ivert2,ivert3,ivert4,rgbv             
           else 
            vertnum=3
            rgbv=rgb5(pow_face3_1,powmin,powmax)
            write(unitno1,*) vertnum,ivert1,ivert2,ivert3,rgbv
            write(unitno3,*) vertnum,ivert1,ivert2,ivert3,rgbv
            rgbv=rgb5(pow_face3_2,powmin,powmax)
            write(unitno1,*) vertnum,ivert3,ivert4,ivert1,rgbv                 
            write(unitno3,*) vertnum,ivert3,ivert4,ivert1,rgbv                                 
          endif
         else
!        nothing here yet for .donut. .EQ. FALSE
                
         endif
         endif
        end do
       end do  
       
!       Last one is different
!       i=M1 because "i+1"=M1, but second terms have 0 because "i" is (i-1)  
        do j=1,N1-1
         ivert1=(M1-1)*N1+j-1
         ivert2=(M1-1)*N1+j
         ivert3=j
         ivert4=j-1
         if  ( (j < b%MV(M1)) .AND. (j < b%MV(1)) ) then  

!        powers go by vertices, but colors need by face
!        pow=b%Zp(I,J)
!        rgbv=rgb5(pow,powmin,powmax)
         pow_vert1=b%Zp(M1,J+1)
         pow_vert2=b%Zp(M1-1,J+1)
         pow_vert3=b%Zp(M1,J) 
         pow_vert4=b%Zp(M1-1,J)
         pow_face4=(pow_vert1+pow_vert2+pow_vert3+pow_vert4)/4
         pow_face3_1=(pow_vert1+pow_vert2+pow_vert3)/3
         pow_face3_2=(pow_vert1+pow_vert3+pow_vert4)/3

         
          if (donut) then
           if (quad) then
            vertnum=4
            rgbv=rgb5(pow_face4,powmin,powmax)
            write(unitno1,*) vertnum,ivert1,ivert2,ivert3,ivert4,rgbv
            write(unitno3,*) vertnum,ivert1,ivert2,ivert3,ivert4,rgbv   
           else
            vertnum=3
            rgbv=rgb5(pow_face3_1,powmin,powmax)
            write(unitno1,*) vertnum,ivert1,ivert2,ivert3,rgbv
            write(unitno3,*) vertnum,ivert1,ivert2,ivert3,rgbv 
            rgbv=rgb5(pow_face3_2,powmin,powmax) 
            write(unitno1,*) vertnum,ivert3,ivert4,ivert1,rgbv             
            write(unitno3,*) vertnum,ivert3,ivert4,ivert1,rgbv
           endif
         else
!        nothing here yet for .donut. .EQ. FALSE

         endif
         endif
        end do  
        
       close (unitno1)       	                            
       close (unitno3)      
    
       end subroutine WriteGeom
