#following code generated by ChatGPT free version on 06/16/2025

def decode_two_byte_unsigned(data: bytes) -> int:
    if not data:
        raise ValueError("Input data is empty.")

    first_byte = data[0]
    c = (first_byte >> 7) & 0x01  # Extract the 'c' bit
    val1 = first_byte & 0x7F     # Extract the 'val1' bits

    if c == 0:
        # One-byte encoding
        return val1
    elif c == 1 and len(data) >= 2:
        # Two-byte encoding
        val2 = data[1]
        return (val1 << 8) | val2
    else:
        raise ValueError("Insufficient data for two-byte encoding.")



def decode_compressed_unsigned(data: bytes):
    """
    Decodes a compressed unsigned int from Microsoft FOUR_BYTE_UNSIGNED_ENCODING format.
    
    Args:
        data (bytes): Bytes input (at least 1 byte).
    
    Returns:
        Tuple[int, int]: (decoded integer value, number of bytes read)
    """
    if len(data) < 1:
        raise ValueError("Insufficient data")

    first = data[0]

    # 1-byte format
    if (first & 0x80) == 0x00:
        return first, 1

    # 2-byte format
    elif (first & 0xC0) == 0x80:
        if len(data) < 2:
            raise ValueError("Insufficient data for 2-byte format")
        value = ((first & 0x3F) << 8) | data[1]
        return value, 2

    # 4-byte format
    elif (first & 0xC0) == 0xC0:
        if len(data) < 4:
            raise ValueError("Insufficient data for 4-byte format")
        value = ((first & 0x3F) << 24) | (data[1] << 16) | (data[2] << 8) | data[3]
        return value, 4

    else:
        raise ValueError("Invalid compressed unsigned integer format")


def decode_two_byte_signed(data: bytes):
    """
    Decodes a signed integer from Microsoft's TWO_BYTE_SIGNED_ENCODING format.
    
    Args:
        data (bytes): Byte array starting with the encoded value.
    
    Returns:
        Tuple[int, int]: (decoded signed integer, number of bytes read)
    """
    if not data:
        raise ValueError("No data provided")

    first = data[0]

    # 1-byte format (7-bit signed int)
    if (first & 0x80) == 0:
        value = first & 0x7F
        # Convert to signed 7-bit value
        if value & 0x40:
            value -= 0x80
        return value, 1

    # 2-byte format (14-bit signed int)
    else:
        if len(data) < 2:
            raise ValueError("Insufficient data for 2-byte signed encoding")
        combined = ((first & 0x7F) << 8) | data[1]
        # Convert to signed 14-bit value
        if combined & 0x2000:
            combined -= 0x4000
        return combined, 2


# from https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/f6f16e2b-8767-42ee-8eff-547780cca952


#unsigned 1 or 2-byte

print(decode_two_byte_unsigned(b'\x7F'))      # 127
print(decode_two_byte_unsigned(b'\x9A\x1B'))  # 0x 1A 1B = 6683 


#signed 1 or 2-byte

samples = [
    bytes.fromhex("3F"),       # +63
    bytes.fromhex("41"),       # -63
    bytes.fromhex("80 00"),    # +0 (2-byte)
    bytes.fromhex("FF FF"),    # -1 (2-byte: 0x3FFF -> two's comp)
    bytes.fromhex("80 01"),    # +1
 
    bytes.fromhex("24"),
    bytes.fromhex("EA C2"),
   
]

for b in samples:
    val, size = decode_two_byte_signed(b)
    print(f"Bytes: {b.hex()} → Value: {val}, Size: {size} bytes")


#unsigned up to 4 bytes


# Hex values for [1-byte, 2-byte, 3-byte  4-byte] encodings
samples = [
    bytes.fromhex("7F"),           # 127 (1-byte)
    bytes.fromhex("81 00"),        # 128 (2-byte)
    bytes.fromhex("C0 00 00 01"),  # 65536 (4-byte)

    bytes.fromhex("AC 24 B5"),
    bytes.fromhex("EA C2 56 4E"),


]

for b in samples:
    val, size = decode_compressed_unsigned(b)
    print(f"Bytes: {b.hex()} → Value: {val}, Size: {size} bytes")








